/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JTextArea;

/**
 *
 * @author Alif
 */
public class v_encpyt extends javax.swing.JFrame {

    /**
     * Creates new form v_inputan
     */
    
    public v_encpyt() {
        initComponents();
         this.setLocationRelativeTo(this);
    }

   
  public String getEncrript() {
        return tulis_teks.getText();
    }

    public void setEncrript(String a) {
        this.tulis_teks.setText(a);
    }

    
     public void addEncryptListener(ActionListener listener) {
        btn_encrypt.addActionListener(listener);
    }
 public void addaboutListener(ActionListener listener) {
        btn_about.addActionListener(listener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_encrypt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tulis_teks = new javax.swing.JTextArea();
        btn_about = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_encrypt.setIcon(new javax.swing.ImageIcon("E:\\Kuliah\\Semester 5\\Kripto\\Projek\\UI\\btn_tes.png")); // NOI18N
        btn_encrypt.setBorderPainted(false);
        btn_encrypt.setContentAreaFilled(false);
        getContentPane().add(btn_encrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 230, 80));

        tulis_teks.setColumns(20);
        tulis_teks.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tulis_teks.setRows(5);
        tulis_teks.setCaretColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tulis_teks);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 240, 110));

        btn_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/About!!.png"))); // NOI18N
        btn_about.setBorderPainted(false);
        btn_about.setContentAreaFilled(false);
        getContentPane().add(btn_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/beranda.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 310, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_encpyt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_encpyt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_encpyt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_encpyt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_encpyt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_about;
    private javax.swing.JButton btn_encrypt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tulis_teks;
    // End of variables declaration//GEN-END:variables
}
