/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author Alif
 */
public class v_hasil extends javax.swing.JFrame {

    /**
     * Creates new form v_hasil
     */
    public v_hasil() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public void setHasil1(String a) {
        this.hasil1.append(a);
    }

    public void setHasil_encrypt(String hasil_encrypt) {
        this.hasil_encrypt.setText(hasil_encrypt);
    }

    public void addKembaliListener(ActionListener listener) {
        btn_kembali.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        hasil_encrypt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        hasil1 = new javax.swing.JTextArea();
        btn_kembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hasil_encrypt.setColumns(20);
        hasil_encrypt.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        hasil_encrypt.setLineWrap(true);
        hasil_encrypt.setRows(5);
        hasil_encrypt.setCaretColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(hasil_encrypt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 240, 140));

        hasil1.setColumns(20);
        hasil1.setFont(new java.awt.Font("Open Sans", 0, 10)); // NOI18N
        hasil1.setLineWrap(true);
        hasil1.setRows(5);
        jScrollPane2.setViewportView(hasil1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 250, 220));

        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_kembali.png"))); // NOI18N
        btn_kembali.setBorderPainted(false);
        btn_kembali.setContentAreaFilled(false);
        btn_kembali.setFocusPainted(false);
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 50, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/hasil.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_hasil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kembali;
    private javax.swing.JTextArea hasil1;
    private javax.swing.JTextArea hasil_encrypt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
